name: sagsin
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - _libgcc_mutex
  - _openmp_mutex
  - bzip2
  - ca-certificates
  - expat
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libstdcxx-ng
  - libuuid
  - ncurses
  - openssl
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib

  - pip:
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==24.3.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - debugpy==1.8.11
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - executing==2.1.0
      - fastjsonschema==2.21.1
      - fonttools==4.55.3
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - geopandas==1.0.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - ipdb==0.13.13
      - ipykernel==6.29.5
      - ipympl==0.9.6
      - ipython==8.31.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mistune==3.1.0
      - mplcursors==0.6
      - mpmath==1.3.0
      - multidict==6.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - notebook-shim==0.2.4
      - numpy==2.2.1
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.48
      - propcache==0.2.1
      - protobuf==5.29.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygad==3.4.0
      - pygments==2.19.0
      - pyogrio==0.10.0
      - pyparsing==3.2.1
      - pyproj==3.7.0
      - python-json-logger==3.2.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.22.3
      - scikit-learn==1.6.1
      - scipy==1.15.0
      - send2trash==1.8.3
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - shapely==2.0.6
      - svgpath2mpl==1.0.0
      - svgpathtools==1.7.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - svgwrite==1.4.3
      - sympy==1.13.1
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - tqdm==4.67.1
      - triton==3.2.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uri-template==1.3.0
      - urllib3==2.3.0
      - wandb==0.19.8
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13
      - yarl==1.18.3
